### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [NielsMasdorp/Sleeply-Android#27]
Hi Niels,

Screenshots look intriguing :) Would you mind publishing the `.apk` here at Github (for the folks without Playstore access)? Best place would probably be the [releases](https://github.com/NielsMasdorp/Sleeply-Android/releases) page – but even if it were inside the repo itself it would at least be accessible :)

Thanks in advance!

**Comment by NielsMasdorp** [comment]
I've added the APK to the releases page!

**Comment by IzzySoft** [comment]
*Boink!* That found me below the table. Fast response, thanks! Unfortunately the release page says: "There aren’t any releases here"?

**Comment by NielsMasdorp** [comment]
Sorry! Forgot to publish.

**Comment by IzzySoft** [comment]
Ah! Yeah, a "draft" can only be seen by team members :) Thanks!
